
services:
  basic_server:
    image: basic_server:0.0.1
    container_name: docker-server
    environment:
    - BASIC_SERVER_PORT=7500
  basic_client:
    image: basic_client:0.0.1
    container_name: docker-client
    volumes:
      - storage_data:/app/data
    environment:
    - BASIC_CLIENT_SERVER_ADDRESS=docker-server:7500
    depends_on:
      basic_server:
        condition: service_started


volumes:
  storage_data: