
services:
  basic_server:
    image: basic_server:0.0.1
    container_name: docker-server
    ports:
      - "8090:8090"
    volumes:
      - storage_data:/app/data
    environment:
      - STORAGE_PATH=/app/data/

volumes:
    storage_data: